version: '2'
services:
  proxy:
    build: dnscrypt/
    image: bigfei/rpi-dnscrypt-proxy
    dns:
      - 192.168.88.254
      - 192.168.88.109
      - 192.168.88.1
      - 114.114.114.114
    environment:
      - LISTEN_ADDR 0.0.0.0:5353
      - RESOLVER_ADDR 208.67.220.220:443
      - PROVIDER_NAME 2.dnscrypt-cert.opendns.com
      - PROVIDER_KEY B735:1140:206F:225D:3E2B:D822:D7FD:691E:A1C3:3CC8:D666:8D0C:BE04:BFAB:CA43:FB79
    restart: always

  unbound:
    build: unbound/
    image: bigfei/rpi-unbound
    dns:
      - 192.168.88.254
      - 192.168.88.109
      - 192.168.88.1
      - 114.114.114.114
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    cap_add:
      - NET_ADMIN
    links:
      - proxy
    environment:
      - FORWARD_ADDR=proxy
      - FORWARD_PORT=5353
      - DNS1=192.168.88.1
      - DNS2=119.29.29.29
    restart: always
