version: '2'
services:
  # proxy:
  #   build: dnscrypt/
  #   image: bigfei/rpi-dnscrypt-proxy
  #   container_name: dns_proxy_telecom
  #   dns:
  #     - 208.67.222.222
  #     - 208.67.220.220
  #   environment:
  #     - LISTEN_ADDR=0.0.0.0:5353
  #     - RESOLVER_ADDR=208.67.220.220:443
  #     - PROVIDER_NAME=2.dnscrypt-cert.opendns.com
  #     - PROVIDER_KEY=B735:1140:206F:225D:3E2B:D822:D7FD:691E:A1C3:3CC8:D666:8D0C:BE04:BFAB:CA43:FB79
  #   restart: always

  proxy:
    build: dnscrypt-v2/
    image: bigfei/rpi-dnscrypt-proxy-v2
    container_name: dns_proxy_telecom
    dns:
      - 40.73.101.101
      - 202.141.178.13
    restart: always

  unbound:
    build: unbound/
    image: bigfei/rpi-unbound
    container_name: dns_unbound_telecom
    depends_on:
      - bind
      - proxy
    dns:
      #- 208.67.222.222
      #- 208.67.220.220
      - 192.168.88.254
      - 202.141.178.13
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    cap_add:
      - NET_ADMIN
    links:
      - proxy
      - bind
    environment:
      - BIND=bind
      - FORWARD_ADDR=proxy
      - FORWARD_PORT=5353
      - DNS1=192.168.88.254
      - DNS2=202.141.162.123
    restart: always

  #isc-dhcp:
  #  build: isc-dhcp/
  #  image: bigfei/rpi-isc-dhcp
  #  container_name: dns_isc_dhcp
  #  links:
  #    - unbound
  #  volumes:
  #    - "~/docker/isc-dhcp:/var/lib/dhcp"
  #  cap_add:
  #    - NET_ADMIN
  #  ports:
  #    - "67:67/udp"
  #    - "674:674/tcp"
  #  restart: always

  bind:
    build: bind/
    image: bigfei/rpi-bind
    container_name: dns_bind
    depends_on:
      - proxy
    ports:
      - "535:53/udp"
    cap_add:
      - NET_ADMIN
    restart: always
