---
version: "2.1"
services:
  smokeping:
    image: ghcr.io/linuxserver/smokeping
    container_name: smokeping
    dns:
      - 192.168.99.53
      - 192.168.99.168
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - "~/docker/smokeping/config:/config"
      - "~/docker/smokeping/data:/data"
    ports:
      - 81:80
    restart: unless-stopped
