version: '2'
services:
  unifi:
    build: .
    image: bigfei/rpi-unifi
    container_name: unifi
    network_mode: "host"
    volumes:
      #- "./certs:/etc/ssl/certs"
      - "~/docker/unifi/data:/usr/lib/unifi/data"
    environment:
      - TZ=Asia/Shanghai
    restart: always
