version: '2'
services:
  unifi:
    build: .
    image: bigfei/rpi-unifi
    container_name: unifi
    dns:
      - 208.67.222.222
      - 208.67.220.220
    ports:
      - "3478:3478/udp"
      - "6789:6789"
      - "8080:8080"
      - "8443:8443"
      - "8880:8880"
      - "8843:8843"
      - "10001:10001/udp"
    volumes:
      - "~/docker/unifi/:/usr/lib/unifi/data"
    environment:
      - LISTEN_ADDR=0.0.0.0:5353
      - RESOLVER_ADDR=208.67.220.220:443
    restart: always
