#!/bin/sh

unboundpid="/var/run/unbound.pid"
blacklistfile="/var/cache/unbound/blacklistfile.list"
chinalist="/var/cache/unbound/forward-zone.China.conf"
applelist="/var/cache/unbound/forward-zone.apple.conf"
hostsfile="/var/cache/unbound/hosts.China.list"

NS1="192.168.99.254"
NS2="119.29.29.29"

blurl="https://raw.githubusercontent.com/oznu/dns-zone-blacklist/master/unbound/unbound-nxdomain.blacklist"

chinaurl="https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf"
appleurl="https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/apple.china.conf"
hostsurl="https://raw.githubusercontent.com/racaljk/hosts/master/hosts"

#chinaurl="https://coding.net/u/felixonmars/p/dnsmasq-china-list/git/raw/master/accelerated-domains.china.conf"
#appleurl="https://coding.net/u/felixonmars/p/dnsmasq-china-list/git/raw/master/apple.china.conf"
#hostsurl="https://coding.net/u/scaffrey/p/hosts/git/raw/master/hosts-files/hosts"

#Blacklist
if [ -e $blacklistfile ]; then rm $blacklistfile; fi
echo "Updating $blacklistfile"
curl --compressed -fsSL -o $blacklistfile $blurl

#ChinaDNS
echo "Updating $chinalist"
curl --compressed -fsSL $chinaurl | grep -v '^#server' | sed 's/server=\//forward-zone:\n\tname: "/g' \
| sed "s/\/114.114.114.114/\"\n\tforward-addr: ${NS1}\n\tforward-addr: ${NS2}\n\tforward-first: yes/g" > $chinalist

#AppleUrl
echo "Updating $applelist"
curl --compressed -fsSL $appleurl | grep -v '^#server' | sed 's/server=\//forward-zone:\n\tname: "/g' \
| sed "s/\/114.114.114.114/\"\n\tforward-addr: ${NS1}\n\tforward-addr: ${NS2}\n\tforward-first: yes/g" > $applelist

#hosts
echo "Updating $hostsfile"
curl --compressed -fsSL $hostsurl | grep -v "^#" | grep . | awk '{print "local-data: \"" $2," A " $1 "\""}' > $hostsfile

#Reload
if [ -e $unboundpid ]; then kill -HUP `cat $unboundpid`; fi
