#!/bin/sh

unboundpid="/var/run/unbound.pid"
adfile="/var/cache/unbound/adfile.list"
malwarefile="/var/cache/unbound/malwarefile.list"
chinalist="/var/cache/unbound/forward-zone.China.conf"
applelist="/var/cache/unbound/forward-zone.apple.conf"
hostsfile="/var/cache/unbound/hosts.China.list"

NS1="192.168.99.254"
NS2="119.29.29.29"

adurl="https://pgl.yoyo.org/adservers/serverlist.php?hostformat=unbound&showintro=0&mimetype=plaintext"
malwareurl="https://mirror1.malwaredomains.com/files/BOOT.zip"
chinaurl="https://coding.net/u/felixonmars/p/dnsmasq-china-list/git/raw/master/accelerated-domains.china.conf"
appleurl="https://coding.net/u/felixonmars/p/dnsmasq-china-list/git/raw/master/apple.china.conf"
#chinaurl="https://raw.githubusercontent.com/bigfei/dnsmasq-china-list/master/accelerated-domains.china.conf"
#hostsurl="https://raw.githubusercontent.com/racaljk/hosts/master/hosts"
hostsurl="https://coding.net/u/scaffrey/p/hosts/git/raw/master/hosts-files/hosts"

#Ads
if [ -e $adfile ]; then rm $adfile; fi
echo "Updating $adfile"
curl --compressed -fsSL -o $adfile $adurl

#Malwares
if [ -e $malwarefile ]; then rm $malwarefile; fi
echo "Updating $malwarefile"
curl -fsSL -o $malwarefile.zip $malwareurl
unzip -p $malwarefile.zip | grep "^PRIMARY" | cut -d " " -f2 > $malwarefile.tmp2
while read i; do
  echo "local-data:\"$i A 127.0.0.1\"" >> $malwarefile
done < $malwarefile.tmp2
rm $malwarefile.tmp*

#ChinaDNS
echo "Updating $chinalist"
curl --compressed -fsSL $chinaurl | grep -v '^#server' | sed 's/server=\//forward-zone:\n\tname: "/g' \
| sed "s/\/114.114.114.114/\"\n\tforward-addr: ${NS1}\n\tforward-addr: ${NS2}\n\tforward-first: yes/g" > $chinalist

#AppleUrl
echo "Updating $applelist"
curl --compressed -fsSL $appleurl | grep -v '^#server' | sed 's/server=\//forward-zone:\n\tname: "/g' \
| sed "s/\/114.114.114.114/\"\n\tforward-addr: ${NS1}\n\tforward-addr: ${NS2}\n\tforward-first: yes/g" > $applelist

#hosts
echo "Updating $hostsfile"
curl --compressed -fsSL $hostsurl | grep -v "^#" | grep . | awk '{print "local-data: \"" $2," A " $1 "\""}' > $hostsfile

#Reload
if [ -e $unboundpid ]; then kill -HUP `cat $unboundpid`; fi
