version: '2'
services:
  nginx:
    build: .
    image: bigfei/rpi-ngx
    ports:
      - "8000:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /home/pirate/docker/ngx:/usr/share/nginx/html
    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "10"
    restart: always
